# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def ExtractPerson(self, record: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PersonName:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractPerson", args={
            "record": record,
        })
        return typing.cast(types.PersonName, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,question: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
            "resume": resume,"question": question,
        })
        return typing.cast(types.Resume, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractSentiment(self, article: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MarketSentimentEntity:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractSentiment", args={
            "article": article,
        })
        return typing.cast(types.MarketSentimentEntity, result.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateCypher(self, question: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CypherQuery:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateCypher", args={
            "question": question,
        })
        return typing.cast(types.CypherQuery, result.cast_to(types, types, stream_types, False, __runtime__))
    def SynthesizeAnswer(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.FinalAnswer:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="SynthesizeAnswer", args={
            "question": question,"context": context,
        })
        return typing.cast(types.FinalAnswer, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractPerson(self, record: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PersonName, types.PersonName]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractPerson", args={
            "record": record,
        })
        return baml_py.BamlSyncStream[stream_types.PersonName, types.PersonName](
          result,
          lambda x: typing.cast(stream_types.PersonName, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PersonName, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractResume(self, resume: str,question: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,"question": question,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          result,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractSentiment(self, article: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MarketSentimentEntity, types.MarketSentimentEntity]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractSentiment", args={
            "article": article,
        })
        return baml_py.BamlSyncStream[stream_types.MarketSentimentEntity, types.MarketSentimentEntity](
          result,
          lambda x: typing.cast(stream_types.MarketSentimentEntity, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MarketSentimentEntity, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateCypher(self, question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CypherQuery, types.CypherQuery]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateCypher", args={
            "question": question,
        })
        return baml_py.BamlSyncStream[stream_types.CypherQuery, types.CypherQuery](
          result,
          lambda x: typing.cast(stream_types.CypherQuery, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CypherQuery, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def SynthesizeAnswer(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FinalAnswer, types.FinalAnswer]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="SynthesizeAnswer", args={
            "question": question,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.FinalAnswer, types.FinalAnswer](
          result,
          lambda x: typing.cast(stream_types.FinalAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FinalAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractPerson(self, record: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractPerson", args={
            "record": record,
        }, mode="request")
        return result
    def ExtractResume(self, resume: str,question: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,"question": question,
        }, mode="request")
        return result
    def ExtractSentiment(self, article: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractSentiment", args={
            "article": article,
        }, mode="request")
        return result
    def GenerateCypher(self, question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateCypher", args={
            "question": question,
        }, mode="request")
        return result
    def SynthesizeAnswer(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeAnswer", args={
            "question": question,"context": context,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractPerson(self, record: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractPerson", args={
            "record": record,
        }, mode="stream")
        return result
    def ExtractResume(self, resume: str,question: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,"question": question,
        }, mode="stream")
        return result
    def ExtractSentiment(self, article: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractSentiment", args={
            "article": article,
        }, mode="stream")
        return result
    def GenerateCypher(self, question: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateCypher", args={
            "question": question,
        }, mode="stream")
        return result
    def SynthesizeAnswer(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeAnswer", args={
            "question": question,"context": context,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))