# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CypherQuery": types.CypherQuery,
    "stream_types.CypherQuery": stream_types.CypherQuery,

    "types.Experience": types.Experience,
    "stream_types.Experience": stream_types.Experience,

    "types.FinalAnswer": types.FinalAnswer,
    "stream_types.FinalAnswer": stream_types.FinalAnswer,

    "types.Person": types.Person,
    "stream_types.Person": stream_types.Person,

    "types.PersonName": types.PersonName,
    "stream_types.PersonName": stream_types.PersonName,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.Skill": types.Skill,
    "stream_types.Skill": stream_types.Skill,


}